### ISSUE TITLE
Bubble 疑似错别字

### ISSUE THREAD

**Issue by sommio** [Nekomoekissaten-SUB/Nekomoekissaten-MIR-Subs#13]
请问
[Dialogue: 1,0:29:19.49,0:29:23.20,Dial-CH,,0,0,0,,**想**我这样喜欢乱来的家伙 必须要时刻盯好](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-MIR-Subs/blob/197715436b8be2b4c8b787fe3692ac894975f5dc/Bubble/%5BNekomoe%20kissaten%5D%20Bubble%20%5BMovie%5D%5BBD%5D.JPSC.ass#L1094)
是否有误？

由[蓥荥](https://bbs.acgrip.com/forum.php?mod=redirect&goto=findpost&ptid=10587&pid=100102&fromuid=33783)发现

**Comment by MIRIMIRIM** [comment]
感谢报错
